# Generated by Django 3.2.3 on 2021-10-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_farmreport_overallreport_websitereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='touxiang.png', null=True, upload_to=''),
        ),
    ]
